/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FollowTheRecordsRouteImport } from './routes/follow-the-records'
import { Route as IndexRouteImport } from './routes/index'

const FollowTheRecordsRoute = FollowTheRecordsRouteImport.update({
  id: '/follow-the-records',
  path: '/follow-the-records',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/follow-the-records': typeof FollowTheRecordsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/follow-the-records': typeof FollowTheRecordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/follow-the-records': typeof FollowTheRecordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/follow-the-records'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/follow-the-records'
  id: '__root__' | '/' | '/follow-the-records'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FollowTheRecordsRoute: typeof FollowTheRecordsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/follow-the-records': {
      id: '/follow-the-records'
      path: '/follow-the-records'
      fullPath: '/follow-the-records'
      preLoaderRoute: typeof FollowTheRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FollowTheRecordsRoute: FollowTheRecordsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
